pipeline {
    agent any

    stages {
        stage('Clone Code') {
            steps {
                git url: 'https://github.com/sakshi-kp/testing-repo.git', branch: 'sak'
            }
        }

        stage('Build and Test') {
            steps {
                echo 'Building and Testing the code...'
            }
        }

        stage('Deploy Code') {
            steps {
                echo 'Deploying the code...'
            }
        }
    }
}



