pipeline {
    agent any

    tools {
        jdk 'java-11'
        maven 'maven'
    }

    stages {
        stage('git-checkout') {
            steps {
                git branch: 'sak', url: 'https://github.com/sakshi-kp/testing-repo.git'
            }
        }

        stage('compile') {
            steps {
                script {
                    sh "mvn compile"
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sh "mvn clean install"
                }
            }
        }
    }
}

