pipeline {
    agent any

    tools {
        jdk 'java-11'
        maven 'maven'
    }

    stages {
        stage('git-checkout') {
            steps {
                git branch: 'sak', url: 'https://github.com/sakshi-kp/testing-repo.git'
            }
        }
        
        stage('compile') {
            steps {
                sh "mvn compile"
            }
        }
        
        stage('Build') {
            steps {
                sh "mvn clean install"
            }
        }
    }
}
